### ISSUE TITLE
Add a sort to the Current board.  

### ISSUE THREAD

**Issue by dstorie80** [Davidtruong02/Wager-Whiz#35]
There is a lot of data to filter through on the current board we need to add a sort drop down that will allow the user to sort through the cards on the current board.  The values should be the same, but it should look at the database for the playerdatas and populate the list from there.  The first two options should be sort by name (based off last name) A-Z (asc) then name A-Z desc, then the other values.

**Comment by akayer19** [comment]
This is now complete.  I added buttons for filtering and Damon added a search bar, that searches for name or team.
